AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  unicorn7

  Sample SAM Template for unicorn7 using Step Functions

Globals:
  Function:
    Timeout: 3
    LoggingConfig:
      LogFormat: JSON

Resources:
  UnicornStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: unicorn-state.asl.json
      DefinitionSubstitutions:
        UnicornTable: !Ref UnicornTable
      Role: !GetAtt UnicornStateMachineExecutionRole.Arn

  UnicornStateMachineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [states.amazonaws.com]
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionsDynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Scan
                  - dynamodb:Query
                Resource: !GetAtt UnicornTable.Arn
  UnicornApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: UnicornApi
      StageName: Prod

  UnicornApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref UnicornApi
      ResourceId: !GetAtt UnicornApi.RootResourceId
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: 
          !Sub arn:aws:apigateway:${AWS::Region}:states:action/StartExecution
        Credentials: !GetAtt UnicornApiExecutionRole.Arn
        RequestTemplates:
          application/json: 
            !Sub |
              {
                "stateMachineArn": "${UnicornStateMachine}",
                "input": "$util.escapeJavaScript($input.json('$'))"
              }
        PassthroughBehavior: WHEN_NO_MATCH
        IntegrationResponses:
          - StatusCode: 200

      MethodResponses:
        - StatusCode: 200

  UnicornApiExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StartStepFunctionsExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !Ref UnicornStateMachine
  UnicornTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: unicorn
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  UnicornStateMachineArn:
    Description: Step Functions State Machine ARN
    Value: !Ref UnicornStateMachine
