AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  unicorn7 (No-Lambda version)

  Demonstrates removing all compute (Lambda)
  and using direct API Gateway -> DynamoDB
  integration to achieve the same functionality.

Resources:
  #
  # 1) DynamoDB Table (same as before)
  #
  UnicornTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: unicorn
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  #
  # 2) IAM Role for API Gateway to assume when calling DynamoDB
  #    (Restricts to PutItem on our 'unicorn' table)
  #
  UnicornApiIntegrationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowPutItemOnUnicornTable
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource: !GetAtt UnicornTable.Arn

  #
  # 3) Serverless API with direct DynamoDB integration
  #
  UnicornApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        openapi: "3.0.1"
        info:
          title: "Unicorn API"
          version: "1.0"
        paths:
          /unicorn:
            post:
              x-amazon-apigateway-integration:
                # Direct AWS integration
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:dynamodb:action/PutItem"
                credentials: !GetAtt UnicornApiIntegrationRole.Arn
                # Map our incoming JSON + request ID into a DynamoDB PutItem
                requestTemplates:
                  application/json: |
                    {
                      "TableName": "unicorn",
                      "Item": {
                        "id": {
                          "S": "$context.requestId"
                        },
                        "Name": {
                          "S": "$input.path('$.Name')"
                        },
                        "Weight": {
                          "S": "$input.path('$.Weight')"
                        }
                      }
                    }
                # Dummy empty response config so we don't fail on defaults
                responses: {}

Outputs:
  #
  # 4) Output the new API's invoke URL
  #
  UnicornApiInvokeURL:
    Description: "API Gateway endpoint URL for POST requests"
    Value: !Sub "https://${UnicornApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/unicorn"
